base_inicial = {
'mes':  [],
'fecha_semana':  [],
'fecha_dia':  [],
'cliente':  [],
'campanya':  [],
'objetivo':  [],
'subojetivo':  [],
'objetivo_final':  [],
'disciplina':  [],
'soporte':  [],
'tipo_coste':  [],
'pagador':  [],
'producto':  [],
'subproducto':  [],
'impresiones':  [],
'clics':  [],
'inversion':  [],
'impresiones_medibles':  [],
'impresiones_visibles':  [],
'views':  [],
'views_25':  [],
'views_50':  [],
'views_75':  [],
'file':  [],
'views_100':  [],
}